version: "3.9"
services:
  pure-jupyter-lab:
    container_name: pure-jupyter-lab
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8889:8888"
    volumes:
      - jupyter-data:/home/jovyan/work
      - ${PWD}/backup:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token='my-token'

volumes:
  jupyter-data:
    name: jupyter-data